/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import file.LibraryFile;
import javax.swing.JOptionPane;
import model.Library;
import model.RegisteredUser;
import model.BookCopy;

/**
 *
 * @author ludov
 */
public class CatalogForm extends javax.swing.JFrame {

    public Library library;
    public LibraryFile file;
    
    public CatalogForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ULbooks = new java.awt.List();
        jLabel19 = new javax.swing.JLabel();
        BTlease = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        TFtitle = new javax.swing.JTextField();
        TFcategory = new javax.swing.JTextField();
        TFyear = new javax.swing.JTextField();
        TFauthor = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        TFcondition = new javax.swing.JTextField();
        TFformat = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        TFstate = new javax.swing.JTextField();
        menu_main = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menu_update_info = new javax.swing.JMenuItem();
        menu_your_leases = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ULbooks.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ULbooksMouseClicked(evt);
            }
        });
        ULbooks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ULbooksActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel19.setText("Books");

        BTlease.setText("Lease");
        BTlease.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTleaseActionPerformed(evt);
            }
        });

        jLabel17.setText("Condition");

        jLabel18.setText("Format");

        TFtitle.setEditable(false);
        TFtitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFtitleActionPerformed(evt);
            }
        });

        TFcategory.setEditable(false);

        TFyear.setEditable(false);

        TFauthor.setEditable(false);

        jLabel13.setText("Title");

        jLabel14.setText("Category");

        jLabel15.setText("Year");

        jLabel16.setText("Author");

        TFcondition.setEditable(false);

        TFformat.setEditable(false);

        jLabel1.setText("State");

        TFstate.setEditable(false);

        jMenu1.setText("Personal");

        menu_update_info.setText("Update Info");
        menu_update_info.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_update_infoActionPerformed(evt);
            }
        });
        jMenu1.add(menu_update_info);

        menu_your_leases.setText("Your Leases");
        menu_your_leases.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_your_leasesActionPerformed(evt);
            }
        });
        jMenu1.add(menu_your_leases);

        menu_main.add(jMenu1);

        jMenu2.setText("Library");

        jMenuItem3.setText("Catalog");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        menu_main.add(jMenu2);

        setJMenuBar(menu_main);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jLabel19)
                .addContainerGap(575, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(ULbooks, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BTlease)
                        .addGap(108, 108, 108))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel16))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TFtitle)
                                    .addComponent(TFcategory)
                                    .addComponent(TFyear)
                                    .addComponent(TFauthor)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel1))
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TFcondition)
                                    .addComponent(TFformat)
                                    .addComponent(TFstate))))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ULbooks, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(TFtitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(TFcategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(TFyear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(TFauthor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(TFcondition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TFformat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TFstate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BTlease)
                        .addGap(38, 38, 38)))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ULbooksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ULbooksActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ULbooksActionPerformed

    private void BTleaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTleaseActionPerformed
        file.LoadLeases(library);
        int YesOrNo = 1;
        RegisteredUser user = library.logged;
        if(user == null)
            JOptionPane.showMessageDialog(null,"Please login before do this action", "Login Required", JOptionPane.INFORMATION_MESSAGE);
        BookCopy copy = (BookCopy) library.books.get(ULbooks.getSelectedIndex());
        if(!library.BookAvaible(copy)){
            YesOrNo = JOptionPane.showConfirmDialog(null,"Ops the book is already taken do you want to order it?","Book already taken", JOptionPane.YES_NO_OPTION);
            if(YesOrNo == 0){
                System.out.println(user.getUsername());
                System.out.println(copy.getTitle());
                library.addOrder(user,copy);
                file.saveOrders(library); 
            }
                
        } 
        else{
        library.addLease(user,copy,null,null);
        file.saveLeases(library);
        }
    }//GEN-LAST:event_BTleaseActionPerformed

    private void ULbooksMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ULbooksMouseClicked
        file.LoadLeases(library);
        BookCopy copy = (BookCopy) library.books.get(ULbooks.getSelectedIndex());
        TFtitle.setText(copy.getTitle());
        TFcategory.setText(copy.getCategory());
        TFyear.setText(Integer.toString(copy.getYear()));
        TFauthor.setText(copy.getAuthor());
        TFcondition.setText(copy.getCondition());
        TFformat.setText(copy.getFormat());
        if(library.BookAvaible(copy))
            TFstate.setText("Avaible");
        else
            TFstate.setText("Taken"); 
    }//GEN-LAST:event_ULbooksMouseClicked

    private void TFtitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFtitleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFtitleActionPerformed

    private void menu_update_infoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_update_infoActionPerformed
        UpdatePersonalInfo updateForm =new UpdatePersonalInfo();
        this.dispose();
        updateForm.setVisible(true);
        updateForm.library = library;
        updateForm.file=file;
        updateForm.TFfname.setText(library.logged.getName());
        updateForm.TFlastname.setText(library.logged.getLname());
        updateForm.TFusername.setText(library.logged.getUsername());
        updateForm.TFpassword.setText(library.logged.getPassword());
        updateForm.TFstreet.setText(library.logged.getStreet());
        updateForm.TFnumber.setText(Integer.toString(library.logged.getNumber()));
        updateForm.TFcity.setText(library.logged.getCity());
    }//GEN-LAST:event_menu_update_infoActionPerformed

    private void menu_your_leasesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_your_leasesActionPerformed
        MyLeasesForm myleasesForm =new MyLeasesForm();
        this.dispose();
        myleasesForm.setVisible(true);
        myleasesForm.library = library;
        myleasesForm.file=file;
        file.LoadBooks(library);
        myleasesForm.showLeaseList();
    }//GEN-LAST:event_menu_your_leasesActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        CatalogForm catalogForm =new CatalogForm();
        this.dispose();
        catalogForm.setVisible(true);
        catalogForm.library = library;
        catalogForm.file=file;
        file.LoadBooks(library);
        catalogForm.showBookList();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

 
    
    void showBookList(){
        int i;
        ULbooks.removeAll();
        for(i=0;i<library.books.size();i++)
            ULbooks.add(library.books.get(i).getTitle());
    }
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CatalogForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CatalogForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CatalogForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CatalogForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CatalogForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTlease;
    public javax.swing.JTextField TFauthor;
    public javax.swing.JTextField TFcategory;
    public javax.swing.JTextField TFcondition;
    public javax.swing.JTextField TFformat;
    private javax.swing.JTextField TFstate;
    public javax.swing.JTextField TFtitle;
    public javax.swing.JTextField TFyear;
    private java.awt.List ULbooks;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuItem jMenuItem3;
    public javax.swing.JMenuBar menu_main;
    private javax.swing.JMenuItem menu_update_info;
    private javax.swing.JMenuItem menu_your_leases;
    // End of variables declaration//GEN-END:variables
}
