/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import file.LibraryFile;
import java.util.ArrayList;
import model.Lease;
import model.Library;
import model.BookCopy;

/**
 *
 * @author ludov
 */
public class MyLeasesForm extends javax.swing.JFrame {

    public Library library;
    public LibraryFile file;
    public MyLeasesForm() {
        initComponents();
    }
    
    public void showLeaseList(){
        int i;
        ArrayList<Lease> myleases = new ArrayList<Lease>();
        ULbooks.removeAll();
        for(i=0;i<library.books.size();i++)
            ULbooks.add(library.books.get(i).getTitle());
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        TFcondition = new javax.swing.JTextField();
        TFformat = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        TFstate = new javax.swing.JTextField();
        ULbooks = new java.awt.List();
        jLabel19 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        TFtitle = new javax.swing.JTextField();
        TFcategory = new javax.swing.JTextField();
        TFyear = new javax.swing.JTextField();
        TFauthor = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menu_update_info = new javax.swing.JMenuItem();
        menu_your_leases = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel13.setText("Title");

        jLabel14.setText("Category");

        jLabel15.setText("Year");

        jLabel16.setText("Author");

        TFcondition.setEditable(false);

        TFformat.setEditable(false);

        jLabel1.setText("State");

        TFstate.setEditable(false);

        ULbooks.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ULbooksMouseClicked(evt);
            }
        });
        ULbooks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ULbooksActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel19.setText("Books");

        jLabel17.setText("Condition");

        jLabel18.setText("Format");

        TFtitle.setEditable(false);
        TFtitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFtitleActionPerformed(evt);
            }
        });

        TFcategory.setEditable(false);

        TFyear.setEditable(false);

        TFauthor.setEditable(false);

        jMenu1.setText("Personal");

        menu_update_info.setText("Update Info");
        menu_update_info.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_update_infoActionPerformed(evt);
            }
        });
        jMenu1.add(menu_update_info);

        menu_your_leases.setText("Your Leases");
        menu_your_leases.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_your_leasesActionPerformed(evt);
            }
        });
        jMenu1.add(menu_your_leases);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Library");

        jMenuItem3.setText("Catalog");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 709, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(47, 47, 47)
                            .addComponent(jLabel19))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(ULbooks, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(72, 72, 72)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel17)
                                        .addComponent(jLabel18)
                                        .addComponent(jLabel1))
                                    .addGap(10, 10, 10)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(TFcondition, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                                        .addComponent(TFstate, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(TFformat, javax.swing.GroupLayout.Alignment.LEADING)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel14)
                                        .addComponent(jLabel13)
                                        .addComponent(jLabel15)
                                        .addComponent(jLabel16))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(TFtitle, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(TFauthor, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(TFyear, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                                        .addComponent(TFcategory, javax.swing.GroupLayout.Alignment.LEADING))))))
                    .addContainerGap(218, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 358, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(49, 49, 49)
                    .addComponent(jLabel19)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(ULbooks, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel13)
                                .addComponent(TFtitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel14)
                                .addComponent(TFcategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel15)
                                .addComponent(TFyear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel16)
                                .addComponent(TFauthor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel17)
                                .addComponent(TFcondition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(TFformat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel18))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(TFstate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel1))))
                    .addContainerGap(40, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ULbooksMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ULbooksMouseClicked
        file.LoadLeases(library);
        BookCopy copy = (BookCopy) library.books.get(ULbooks.getSelectedIndex());
        TFtitle.setText(copy.getTitle());
        TFcategory.setText(copy.getCategory());
        TFyear.setText(Integer.toString(copy.getYear()));
        TFauthor.setText(copy.getAuthor());
        TFcondition.setText(copy.getCondition());
        TFformat.setText(copy.getFormat());
        TFstate.setText(Boolean.toString(library.BookAvaible(copy)));
    }//GEN-LAST:event_ULbooksMouseClicked

    private void ULbooksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ULbooksActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ULbooksActionPerformed

    private void TFtitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFtitleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFtitleActionPerformed

    private void menu_update_infoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_update_infoActionPerformed
        UpdatePersonalInfo updateForm =new UpdatePersonalInfo();
        this.dispose();
        updateForm.setVisible(true);
        updateForm.library = library;
        updateForm.file=file;
        updateForm.TFfname.setText(library.logged.getName());
        updateForm.TFlastname.setText(library.logged.getLname());
        updateForm.TFusername.setText(library.logged.getUsername());
        updateForm.TFpassword.setText(library.logged.getPassword());
        updateForm.TFstreet.setText(library.logged.getStreet());
        updateForm.TFnumber.setText(Integer.toString(library.logged.getNumber()));
        updateForm.TFcity.setText(library.logged.getCity());
    }//GEN-LAST:event_menu_update_infoActionPerformed

    private void menu_your_leasesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_your_leasesActionPerformed
        MyLeasesForm myleasesForm =new MyLeasesForm();
        this.dispose();
        myleasesForm.setVisible(true);
        myleasesForm.library = library;
        myleasesForm.file=file;
        file.LoadBooks(library);
        myleasesForm.showLeaseList();
    }//GEN-LAST:event_menu_your_leasesActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        CatalogForm catalogForm =new CatalogForm();
        this.dispose();
        catalogForm.setVisible(true);
        catalogForm.library = library;
        catalogForm.file=file;
        file.LoadBooks(library);
        catalogForm.showBookList();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MyLeasesForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MyLeasesForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MyLeasesForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MyLeasesForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MyLeasesForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField TFauthor;
    public javax.swing.JTextField TFcategory;
    public javax.swing.JTextField TFcondition;
    public javax.swing.JTextField TFformat;
    private javax.swing.JTextField TFstate;
    public javax.swing.JTextField TFtitle;
    public javax.swing.JTextField TFyear;
    private java.awt.List ULbooks;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem menu_update_info;
    private javax.swing.JMenuItem menu_your_leases;
    // End of variables declaration//GEN-END:variables
}
